name: Publish Storybook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Release Storybook
        run: yarn workspace @hastics/components storybook:deploy --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.HASTICS_STORYBOOK_TOKEN }}
